name: On Merge to main
on:
  pull_request:
    branches:
      - main
    types:
    - closed

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - name: Build a job
      run: |
       echo: "Building a job"